name: "godot-ci export"
on:
  push:
    branches:
      - release-pc

env:
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: shattered-reality

jobs:
  export-deploy-windows:
    name: Windows Export and Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          # cd $EXPORT_NAME
          godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: windows
            ITCH_GAME: shattered-reality
            ITCH_USER: Oeslian
            PACKAGE: build/windows


  export-deploy-linux:
    name: Linux Export and Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          # cd $EXPORT_NAME
          godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: linux
            ITCH_GAME: shattered-reality
            ITCH_USER: Oeslian
            PACKAGE: build/linux

  export-deploy-mac:
    name: Mac Export and Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
            CHANNEL: mac
            ITCH_GAME: shattered-reality
            ITCH_USER: Oeslian
            PACKAGE: build/mac
